### ISSUE TITLE
Remove CSS Properties [box shadows]

### ISSUE THREAD

**Issue by cmcWebCode40** [vincentdoerig/latex-css#17]
# Description
I used this CDNlink on my SPA page and it worked well but for some element used as cards that have box-shadows doesn't comply with the pattern 

# Solution
I'm suggesting that on default CSS properties like `box-shadow` should removed

**Comment by vincentdoerig** [comment]
Could you please send the markup for the card so that I can try to reproduce the issue and see what elements are affected?

**Comment by cmcWebCode40** [comment]
You mean the card I used in testing it ?

**Comment by vincentdoerig** [comment]
Yes exactly

**Comment by cmcWebCode40** [comment]
I tested it with a project i'm building with react and  scss for styling 
```scss
.product {
  position: relative;
  background: $white;
  text-align: center;
  cursor: pointer;
  width: 75%;
  border-radius: $border-radius;
  margin: 2rem auto;
  box-shadow: $box-shadow;
}
```
actually the value for my box-shadow property is 
```scss
$box-shadow: -1px 3px 18px 1px #f4f4f4, -3px 6px 18px -3px #f4f4f4;
```
