### ISSUE TITLE
French translation for table caption prefix discrepance with LaTeX Babel

### ISSUE THREAD

**Issue by vihuna** [vincentdoerig/latex-css#73]
From LaTeX `babel-french` [package](https://www.ctan.org/tex-archive/macros/latex/contrib/babel-contrib/french), it seems they use **Table** as translation:

```latex
\SetString{\tablename}{Table}
```
But in LaTeX.css `lang/fr.css`  **Tableau** is the word used for French translation:

```css
:lang(fr) caption::before { content: 'Tableau ' counter(caption) '. ' !important; }
```
I don't speak French, so I can't say more about this.
